#ifndef INCLUDE_COLORS_HPP
#define INCLUDE_COLORS_HPP

#include <cstdint>

struct color_t {
    std::uint8_t r, g, b;
};

struct color_float_t {
    float r, g, b;
};

#define NORMALIZE_COLOR(color) color_float_t{color.r/255.0, color.g/255.0, color.b/255.0}
#define EXPAND_COLOR(color) color.r, color.g, color.b
#define REPEAT3(color) color, color, color

#define COLOR_BLACK_3f          EXPAND_COLOR(NORMALIZE_COLOR(COLOR_BLACK))
#define COLOR_DARKGREY_3f       EXPAND_COLOR(NORMALIZE_COLOR(COLOR_DARKGREY))
#define COLOR_DARKBLUE_3f       EXPAND_COLOR(NORMALIZE_COLOR(COLOR_DARKBLUE))
#define COLOR_DARKGREEN_3f      EXPAND_COLOR(NORMALIZE_COLOR(COLOR_DARKGREEN))
#define COLOR_GREY_3f           EXPAND_COLOR(NORMALIZE_COLOR(COLOR_GREY))
#define COLOR_GREEN_3f          EXPAND_COLOR(NORMALIZE_COLOR(COLOR_GREEN))
#define COLOR_RED_3f            EXPAND_COLOR(NORMALIZE_COLOR(COLOR_RED))
#define COLOR_YELLOW_3f         EXPAND_COLOR(NORMALIZE_COLOR(COLOR_YELLOW))
#define COLOR_WHITE_3f          EXPAND_COLOR(NORMALIZE_COLOR(COLOR_WHITE))
#define COLOR_BLUE_3f           EXPAND_COLOR(NORMALIZE_COLOR(COLOR_BLUE))
#define COLOR_LIGHTBLUE_3f      EXPAND_COLOR(NORMALIZE_COLOR(COLOR_LIGHTBLUE))
#define COLOR_ORANGE_3f         EXPAND_COLOR(NORMALIZE_COLOR(COLOR_ORANGE))
#define COLOR_LIME_3f           EXPAND_COLOR(NORMALIZE_COLOR(COLOR_LIME))
#define COLOR_MAGENTA_3f        EXPAND_COLOR(NORMALIZE_COLOR(COLOR_MAGENTA))
#define COLOR_NAVY_3f           EXPAND_COLOR(NORMALIZE_COLOR(COLOR_NAVY))
#define COLOR_AQUA_3f           EXPAND_COLOR(NORMALIZE_COLOR(COLOR_AQUA))
#define COLOR_CRIMSON_3f        EXPAND_COLOR(NORMALIZE_COLOR(COLOR_CRIMSON))
#define COLOR_FLBLUE_3f         EXPAND_COLOR(NORMALIZE_COLOR(COLOR_FLBLUE))
#define COLOR_BISQUE_3f         EXPAND_COLOR(NORMALIZE_COLOR(COLOR_BISQUE))
#define COLOR_CHARTREUSE_3f     EXPAND_COLOR(NORMALIZE_COLOR(COLOR_CHARTREUSE))
#define COLOR_BROWN_3f          EXPAND_COLOR(NORMALIZE_COLOR(COLOR_BROWN))
#define COLOR_CORAL_3f          EXPAND_COLOR(NORMALIZE_COLOR(COLOR_CORAL))
#define COLOR_GOLD_3f           EXPAND_COLOR(NORMALIZE_COLOR(COLOR_GOLD))
#define COLOR_GREENYELLOW_3f    EXPAND_COLOR(NORMALIZE_COLOR(COLOR_GREENYELLOW))
#define COLOR_INDIGO_3f         EXPAND_COLOR(NORMALIZE_COLOR(COLOR_INDIGO))
#define COLOR_IVORY_3f          EXPAND_COLOR(NORMALIZE_COLOR(COLOR_IVORY))
#define COLOR_LAWNGREEN_3f      EXPAND_COLOR(NORMALIZE_COLOR(COLOR_LAWNGREEN))
#define COLOR_SEAGREEN_3f       EXPAND_COLOR(NORMALIZE_COLOR(COLOR_SEAGREEN))
#define COLOR_LIMEGREEN_3f      EXPAND_COLOR(NORMALIZE_COLOR(COLOR_LIMEGREEN))
#define COLOR_MIDNIGHTBLUE_3f   EXPAND_COLOR(NORMALIZE_COLOR(COLOR_MIDNIGHTBLUE))
#define COLOR_MAROON_3f         EXPAND_COLOR(NORMALIZE_COLOR(COLOR_MAROON))
#define COLOR_OLIVE_3f          EXPAND_COLOR(NORMALIZE_COLOR(COLOR_OLIVE))
#define COLOR_ORANGERED_3f      EXPAND_COLOR(NORMALIZE_COLOR(COLOR_ORANGERED))
#define COLOR_PINK_3f           EXPAND_COLOR(NORMALIZE_COLOR(COLOR_PINK))
#define COLOR_SPRINGGREEN_3f    EXPAND_COLOR(NORMALIZE_COLOR(COLOR_SPRINGGREEN))
#define COLOR_TOMATO_3f         EXPAND_COLOR(NORMALIZE_COLOR(COLOR_TOMATO))
#define COLOR_YELLOWGREEN_3f    EXPAND_COLOR(NORMALIZE_COLOR(COLOR_YELLOWGREEN))
#define COLOR_MEDIUMAQUA_3f     EXPAND_COLOR(NORMALIZE_COLOR(COLOR_MEDIUMAQUA))
#define COLOR_PURPLE_3f         EXPAND_COLOR(NORMALIZE_COLOR(COLOR_PURPLE))
#define COLOR_MEDIUMMAGENTA_3f  EXPAND_COLOR(NORMALIZE_COLOR(COLOR_MEDIUMMAGENTA))
#define COLOR_SKY_3f            EXPAND_COLOR(NORMALIZE_COLOR(COLOR_SKY))
#define COLOR_SEA_3f            EXPAND_COLOR(NORMALIZE_COLOR(COLOR_SEA))

constexpr color_t COLOR_BLACK = { 0x00, 0x00, 0x00 };
constexpr color_t COLOR_DARKGREY = { 0xA, 0xA, 0xA };
constexpr color_t COLOR_DARKBLUE = { 0x0A, 0x14, 0x80 };
constexpr color_t COLOR_DARKGREEN = { 0x00, 0x16, 0x00 };
constexpr color_t COLOR_GREY = { 0xAF, 0xAF, 0xAF };
constexpr color_t COLOR_GREEN = { 0x33, 0xAA, 0x33 };
constexpr color_t COLOR_RED = { 0xAA, 0x33, 0x33 };
constexpr color_t COLOR_YELLOW = { 0xFF, 0xFF, 0x00 };
constexpr color_t COLOR_WHITE = { 0xFF, 0xFF, 0xFF };
constexpr color_t COLOR_BLUE = { 0x00, 0x00, 0xFF };
constexpr color_t COLOR_LIGHTBLUE = { 0x33, 0xCC, 0xFF };
constexpr color_t COLOR_ORANGE = { 0xFF, 0x99, 0x00 };
constexpr color_t COLOR_LIME = { 0x10, 0xF4, 0x41 };
constexpr color_t COLOR_MAGENTA = { 0xFF, 0x00, 0xFF };
constexpr color_t COLOR_NAVY = { 0x00, 0x00, 0x80 };
constexpr color_t COLOR_AQUA = { 0xF0, 0xF8, 0xFA };
constexpr color_t COLOR_CRIMSON = { 0xDC, 0x14, 0x3C };
constexpr color_t COLOR_FLBLUE = { 0x64, 0x95, 0xED };
constexpr color_t COLOR_BISQUE = { 0xFF, 0xE4, 0xC4 };
constexpr color_t COLOR_CHARTREUSE = { 0x7F, 0xFF, 0x00 };
constexpr color_t COLOR_BROWN = { 0xA5, 0x2A, 0x2A };
constexpr color_t COLOR_CORAL = { 0xFF, 0x75, 0x50 };
constexpr color_t COLOR_GOLD = { 0xB8, 0x86, 0x0B };
constexpr color_t COLOR_GREENYELLOW = { 0xAD, 0xFF, 0x2F };
constexpr color_t COLOR_INDIGO = { 0x4B, 0x00, 0xB0 };
constexpr color_t COLOR_IVORY = { 0xFF, 0xFF, 0x82 };
constexpr color_t COLOR_LAWNGREEN = { 0x7C, 0xFC, 0xC0 };
constexpr color_t COLOR_SEAGREEN = { 0x20, 0xB2, 0xAA };
constexpr color_t COLOR_LIMEGREEN = { 0x32, 0xCD, 0x32 };
constexpr color_t COLOR_MIDNIGHTBLUE = { 0x19, 0x19, 0x70 };
constexpr color_t COLOR_MAROON = { 0x80, 0x00, 0x00 };
constexpr color_t COLOR_OLIVE = { 0x80, 0x80, 0x00 };
constexpr color_t COLOR_ORANGERED = { 0xFF, 0x45, 0x00 };
constexpr color_t COLOR_PINK = { 0xFF, 0xC0, 0xCB };
constexpr color_t COLOR_SPRINGGREEN = { 0x00, 0xFF, 0x7F };
constexpr color_t COLOR_TOMATO = { 0xFF, 0x63, 0x47 };
constexpr color_t COLOR_YELLOWGREEN = { 0x9A, 0xCD, 0x3F };
constexpr color_t COLOR_MEDIUMAQUA = { 0x83, 0xBF, 0xBF };
constexpr color_t COLOR_PURPLE = { 0x80, 0x00, 0x80 };
constexpr color_t COLOR_MEDIUMMAGENTA = { 0x8B, 0x00, 0x8B };
constexpr color_t COLOR_SKY = { 0x66, 0x77, 0x90 };
constexpr color_t COLOR_SEA = { 0x3D, 0x4A, 0x5C };

#endif /* INCLUDE_COLORS_HPP */